- README.md
* I had to install libffi-dev on debian, or pip install would fail at 'Running setup.py install for CFFI'
* add 0.4-dev installation instructions from git master
> [doc] update setup instructions

- lisp/i18n/lisp_fr.ts
Following https://github.com/FrancescoCeruti/linux-show-player/issues/38#issuecomment-262809218 advice. Hope that helps.
@aroomthedoomed : You're translation was really good! I've been making some changes/fixes. I hope that helps you. Feel free to comment those changes.
> French translation review.

- lisp/application.py
- lisp/plugins/cart_layout/__init__.py
- lisp/plugins/cart_layout/default.json
- lisp/plugins/cart_layout/settings.py
- lisp/ui/settings/app_pages/app_general.py
Summary:
1. ~Provide missing default value~ Remove mention of defunct option from UI;
2. Resolve name conflict with variable `layout` in `application.py`;
3. Find the correct choice in the settings page.
(See commit messages for details)
> Layout settings fixes

- lisp/core/decorators.py
- lisp/core/signal.py
- lisp/cues/cue.py
- lisp/cues/media_cue.py
- lisp/modules/action_cues/command_cue.py
- lisp/modules/action_cues/volume_control.py
- lisp/modules/remote/controller.py
> Fix compatibility with Python 3.7, async is now a reserved word

- lisp/plugins/midi/midi_utils.py
Currently, when using the `develop` branch, attempting to edit an already edited MIDI cue causes `lisp` to crash.
(Note: This was fixed for the `v0.5.1` release in 20bb7a2, albeit with a different solution. It appears that that fix was not migrated to the `develop` branch.)
Steps to reproduce:
* Open `lisp` (either layout).
* Create a MIDI Cue.
* Use appropriate action to open the edit dialog.
* Press "OK" (Don't have to make any actual edits) to save and close the dialog.
* Re-open the dialog.
* Observe the crash.
The crash occurs because `_spec` is not a property of `mido`'s `Message` class.
The fix in this PR changes `str_msg_to_dict` to use `mido`'s methods to convert from `str` to `dict`, rather than trying to duplicate functionality.
(PR also includes a clean-up of the companion …
> Fix crash when editing a MIDI cue a second time

- lisp/cues/media_cue.py
When the fade-down duration of a media cue is > 0, and either:
* The fade-up duration is 0; or
* The resume-button is set to resume (instead of resume-and-fade-up) in the preferences
Then:
* Pausing will fade-down and pause track
* Resuming again will resume playback, but not restore volume
This changeset fixes that (for the `master` branch). (The `develop` branch suffers from the same problem, so I don't know if you wish to also apply this patch to that, or something else. You're the boss :wink:)
> Set volume in the case of no fade-up

- Pipfile
- lisp/__init__.py
- lisp/main.py
- lisp/plugins/__init__.py
- lisp/plugins/presets/lib.py
On Linux systems, it is generally recommended to follow the [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) when determining where to store user configuration, file-level caches, and user-specific application data.
Thus, as of this PR:
* *configuration* is now stored at `$XDG_CONFIG_HOME/linux_show_player`
(by default: `~/.config/linux_show_player`)
* *presets* are now stored under `$XDG_DATA_HOME/linux_show_player/presets`
(by default: `~/.local/share/linux_show_player/presets`)
* *logs* are now stored under `$XDG_CACHE_HOME/linux_show_player/logs`
(by default: `~/.cache/linux_show_player/logs`)
On the downside, this PR does add another python dependency. However, the advantage of using the `appdirs` python module (instead of hard-coding …
> Follow XDG spec when storing user data.

- lisp/layout/cue_layout.py
- lisp/plugins/list_layout/layout.py
- lisp/ui/mainwindow.py
Hello, 
1) I detect a minor problem when I want to save a file. 
Indeed, when I close the session and I don't save the session, a message box is activated (with 3 options: "Close without Saving", "Cancel" and "Save"). If I click in "Save" (it opens a widget with all my directories and files) and close by mistake the widget, I quit the application. However, I think it will be better if we close by mistake (and so we don't save anything), we should be redirected on the app.
2) Morever, I notice also that there is no shortcut to remove a cue. So I decided to put it (I hope it will be useful because it's an action that I use regularly).
Here are some pictures of the problem (for the first problem):
I hope I worked on the correct branch this time. To be honest, it was not intentional to fix …
> Minor changes: Return to player if the user don't save and add shortcut to remove cue

- lisp/plugins/cart_layout/page_widget.py
The code was incorrectly calculating the size of cue-widgets on a page.
This is observable by:
1. Create a new showfile using the Cart Layout.
2. Create a cue (any type) and place it in the bottom-right of the tab page.
3. Right-click somewhere in the lower-right quadrant of the cue-widget.
4. Close the resulting context menu.
5. Right click somewhere around or on the coloured dot in the top left of the cue-widget.
6. Observe the application crash to desktop
Why? After calculating the correct width and height, the code was then adding the value of the variable `space` (six pixels on my system) to both calculated dimensions. As the cue-widgets are placed further and further away from position `(0, 0)`, there is an ever-increasing margin where the top and left sides of a cue-widget are …
> Correct the Cart Layout's page_widget::indexAt method

- lisp/plugins/list_layout/list_view.py
(Should fix #180, caused by changes in fd883a43.)
For some reason the `QTreeWidgetItem` passed as `previous` to `__currentItemChanged` retains its former index (despite the fact that logically, by the time the method is called, a different `QTreeWidgetItem` should reside there now) but appears to have lost its references to its "column widgets".
Thus, when we request each of the "column widgets" in turn, they can't be found.
When removing a row, we don't really need to set the styles of a `QTreeWidgetItem` that's being removed... so let's not.
As to moving a row, the `QTreeWidgetItem` returned by `self.takeTopLevelItem` in `__cueMoved` has the "column widgets" we're looking for. So let's apply `__updateItemStyle` on that instead.
> Potential fix for issue 180

- lisp/ui/ui_utils.py
The extra backslash leads to a `SyntaxError`  when compiling the module to byte-code (Python 3.8):
```
writing byte-compilation script '/home/chris/tmp/tmpzjp2l7dq.py'
/usr/bin/python /home/chris/tmp/tmpzjp2l7dq.py
File "usr/lib/python3.8/site-packages/lisp/ui/ui_utils.py", line 104
return sorted(iterable, key=tr_key, reverse=reverse)\
^
SyntaxError: unexpected EOF while parsing
removing /home/chris/tmp/tmpzjp2l7dq.py
```
> Remove backslash from end of last line

- lisp/plugins/cart_layout/page_widget.py
- lisp/plugins/gst_backend/gst_backend.py
- lisp/plugins/list_layout/list_view.py
Hi,
I was looking to use linux-show-player in our local radio and missing the ability to drop files from the file manager was a noted sore point, hence this pull request. It's made of two commits, one for the list view (this was our primary demand) and one for the card layout.
I only tested it with Nautilus but I don't think it has anything specific and it should work as is with other file managers. (also I never used PyQt before)
> Drag'n drop files from file manager (issue #137)

- lisp/main.py
(Written in response to the recent various "icons not being drawn" comments.)
`qt5ct` creates (or requires the user to create) the environment argument `QT_QPA_PLATFORMTHEME` with the value `qt5ct`.
The code supplied below detects the existence of the environment argument, checks its value, and if relevant adds a (blank) argument to be passed to the invocation of `QApplication`. This appears to causes Qt to ignore the environment value and fallback on the default platform theme.
----
A fix doesn't seem to be needed for the `0.6`/`develop` branch.
> [0.5.x] Detect qt5ct and workaround it

- lisp/plugins/list_layout/playing_widgets.py
- lisp/ui/widgets/dbmeter.py
The markings shown are those determined (by the code) to fit the space available without overlapping.
Examples:
> Draw scale markings on level meters

- lisp/plugins/__init__.py
> ##### s0600204:
> Which begs the question - how do you envision plugin installation working in the future? [...] Hypothetically, how would these custom plugins be "packaged" so that someone else can easily "install" them?
>
> ##### FrancescoCeruti:
> I've thought a bit about that, ideally you could simply have a directory in the user home (under .linux_show_player), where LiSP looks for user installed plugins. [...] They can be packaged as zip files or similar with a metadata file.
This set of changes is an attempt to permit the above.
With this PR, it is possible to place a plugin in the folder `$XDG_DATA_HOME/LinuxShowPlayer/$LiSP_Version/plugins/` (e.g. `~/.local/share/LinuxShowPlayer/0.6/plugins/`) and LiSP will load it on next program restart.
As an example, I've created a plugin …
> Support loading plugins from a User's home directory

- lisp/plugins/controller/protocols/osc.py
- lisp/plugins/osc/osc_server.py
Having two `add_method()` with the same `path` and `args` arguments doesn't seem to
work - the second callback is never called.
This should resolve an issue @bgberk has been reporting on gitter.
> Correct OSC callback setup

- lisp/ui/widgets/pagestreewidget.py
(For the record, I run the `xfce4` desktop environment on Arch Linux, and I am fully up-to-date. I reset LiSP to the latest dev/0.6 state, and disabled/removed all custom code/plugins.)
I've recently been having a problem with running LiSP on my computer.
Specifically: almost every time I try to open LiSP's Application Preferences dialog, `xfwm4` (`xfce4`'s window manager) would coredump and restart. Also, LiSP would stop responding to user input.
After two days of debugging, I traced this to the change you see in the diff.
I'm not 100% sure *why* this should fix the issue, but I suspect it might be a race condition. Reasoning:
* In the process of debugging, it came up that the underlying `GDK` system interacts with the the `X Windowing System` asynchronously.
* Starting `xfwm4` like so: …
> Resolve an issue that was causing xfwm4 on Arch to coredump

- lisp/core/plugin.py
- lisp/plugins/__init__.py
- lisp/ui/icons/lisp/led-error-outline.svg
- lisp/ui/icons/lisp/led-off-outline.svg
- lisp/ui/icons/lisp/led-pause-outline.svg
- lisp/ui/icons/lisp/led-running-outline.svg
- lisp/ui/settings/app_pages/plugins.py
This PR adds a way of acquiring the status or state of a plugin.
It is now possible to query a plugin directly to see if it is loaded or disabled; and to request a suitable status icon and tooltip for use in GUI ([preview](https://user-images.githubusercontent.com/2053873/73013176-ba584500-3e0f-11ea-988c-d9cb32f81b1b.jpg)).
There are also a few more status icon varieties.
----
Thoughts:
* Would it be worth adding methods to the `Plugin` class that can be used to check if it is in Error or Warning?
- If Plugin-A could optionally use Plugin-B, then Plugin-A can simply check if Plugin-B is loaded or not. The fact that Plugin-B is in error is (for now) irrelevant.
- Whilst the only current error is that dependencies are not satisfied (and this also prevents the plugin from being loaded), it …
> Implement a form of "plugin status"

- lisp/plugins/list_layout/playing_widgets.py
Currently when a `GstMediaCue` added to a List Layout with the input of the cue's pipeline set to "Preset Input" is played, an error is emitted and the cue doesn't appear in the "Playing Cues" section. (A further error is emitted when the cue ends or is stopped.)
The initial error is emitted because the waveform code attempts to generate a waveform from the cue's media file, but the Preset Input is not sourced from one.
This PR checks that the cue has a file URI, and if not fallbacks to the other slider representation.
> Don't use waveform slider when playing Media cues with "Preset" source

- lisp/plugins/gst_backend/config/__init__.py
- lisp/plugins/gst_backend/config/alsa_sink.py
- lisp/plugins/gst_backend/elements/alsa_sink.py
- lisp/plugins/gst_backend/gst_backend.py
- lisp/plugins/gst_backend/settings/alsa_sink.py
The chosen ALSA device will be used by new (Gst)Media Cues, instead of using the system's default device.
Previously if a user wished to use - for example - a USB soundcard, then the user would have to manually set that in every cue. Now the user may set it once, globally, and all (Gst)Media cues created afterwards will use that device.
----
The new setting may be found/configured under File > Preferences; Plugins > GStreamer > ALSA Default Device
> Implement ability for set a preferred default ALSA device

- lisp/ui/themes/dark/theme.qss
Recent commit 6fa0bfda0453d tweaked the dark-theme palette. This resulted in the List Layout's `RunningCueWidget`s to change appearance as depicted below (left: before; right: after):
(Seems to be a side-effect of removing the `background-color` rule from the `QWidget` ruleset within the stylesheet.)
I'm guessing that this change to the background of the `RunningCueWidget` wasn't intended, so this PR restores it:
You might notice that the new background is `palette(mid)` instead of `palette(window)` (the latter would be closer to the appearance pre- 6fa0bfda0453d). Feel free to change that if you prefer.
> Restore background to `RunningCueWidget` instances

- lisp/modules/action_cues/index_action_cue.py
With this PR the combobox now gets updated under the following circumstances:
* When the user checks/unchecks the "Relative Index" box
* When the user reopens the cue settings dialog (after saving the cue previously, or after loading an existing show file)
Fixes #227
(This is already fixed within LiSP version `0.6`, and this PR is loosely based on the code used there.)
> Update IndexAction cue's combobox of actions

- lisp/plugins/osc/osc_cue.py
As it is no longer possible (since f937bde800a7) for `Fader`s to be paused, it is also no longer possible to pause running (e.g. fading) OSC cues.
> Remove the OSC cue's 'Pause' action

- lisp/layouts/list_layout/cue_list_view.py
fix #230 
It interfere with keyboard shortcut. When a shortkey is pressed the next cue that begin with the typed letter is selected.
> fix #230 Remove search on keypress on list layout

- lisp/ui/mainwindow.py
Previously the window title was only updated when an open file was saved, a cue was edited, or an undo/redo occurred.
This had interesting side effects, such as when one showfile was saved and the user then opens a second: LiSP's titlebar still showed the name of the saved file and not that of the just-loaded file.
Related to #241
> Update window title on file creation and load

- lisp/modules/gst_backend/gst_media.py
fix #240 
Do not seek to start_time if media cue is paused
> #240 fix a paused audio cue is not resumed but restarted if start-time has been set

- lisp/cues/cue.py
- lisp/cues/media_cue.py
- lisp/plugins/gst_backend/gst_media.py
- lisp/ui/settings/cue_pages/cue_general.py
- lisp/ui/widgets/cue_actions.py
This PR adds a new "Loop Release" action to Media Cues.
When triggered on a cue that is looping, it causes the current loop to finish before stopping the cue; in comparison to the "Stop" action which stops the cue straight away (with or without a fade).
I personally use it on shows for things such as phone ringing sound effects (which sound odd if stopped abruptly); whilst a recent user on the gitter chat mentioned that this sort of functionality might be useful for "vamping": where a short stretch of music is looped for a period of time that varies between performances (for instance: underscoring the dialogue between verses in a song).
> Implement a Loop-Release CueAction

- lisp/plugins/list_layout/layout.py
At the moment, the "Show Index Column" option (in the "Layout" menu) is saved inverted to what it's set.
This means that if the Index Column is shown and the user then "saves" the showfile, the Column is saved as hidden, causing the column to not be shown when the showfile is next loaded. The reverse is also true.
This PR corrects this.
> Correctly save index column visibility

- lisp/application.py
**Abstract**
This PR is meant to address issue #335 - Application crashes on save with bad session data.
**Description**
This PR changes the logic of `__save_to_file()` in `application.py` by first checking to ensure the JSON serialization of session data was successful before opening the file, writing data, changing application title and saving session.
In the event there is data present in the in-memory session which is **not** serializable into JSON (for example, if a plugin `GstProperty` returns a GObject rather than a simple type) a meaningful error message will be displayed to the user.
> Improvement: Prevent application crash on Save Session

- lisp/plugins/action_cues/collection_cue.py
- lisp/plugins/action_cues/command_cue.py
- lisp/plugins/action_cues/index_action_cue.py
- lisp/plugins/action_cues/seek_cue.py
- lisp/plugins/action_cues/stop_all.py
- lisp/plugins/action_cues/volume_control.py
- lisp/plugins/midi/midi_cue.py
- lisp/plugins/osc/osc_cue.py
This change adds Pause and Resume CueActions to all cues.  That way they can pause with the Pause All button along with Media Cues.  This is a bug fix for issue #340.
> Adding Pause and Resume actions to all non-media cues
